### ISSUE TITLE
Unable to query successful response from server

### ISSUE THREAD

**Issue by rreusser** [OctoLinker/live-resolver#45]
It seems perhaps something is wrong on heroku, which has the downstream effect of breaking the octolinker extension.

**Expected behavior**: Querying the example url [https://githublinker.herokuapp.com/q/bower/backbone](https://githublinker.herokuapp.com/q/bower/backbone) returns the expected response.

**Observed behavior**: All queries seem to fail. A couple examples:

Some queries return an app-level 500 error:

```bash
$ curl -I https://githublinker.herokuapp.com/q/bower/backbone
HTTP/1.1 500 Internal Server Error
Server: Cowboy
Connection: keep-alive
Content-Type: application/json; charset=utf-8
Cache-Control: no-cache
Content-Length: 96
Vary: accept-encoding
Date: Mon, 02 Oct 2017 20:31:41 GMT
Via: 1.1 vegur

$ curl https://githublinker.herokuapp.com/q/bower/backbone
{"message":"An internal server error occurred","statusCode":500,"error":"Internal Server Error"}% 
```

Some queries return a heroku-level 503 Service Unavailable error (30s timeout, I think):

```bash
$ curl -I https://githublinker.herokuapp.com/q/npm/browserify
HTTP/1.1 503 Service Unavailable
Connection: keep-alive
Server: Cowboy
Date: Mon, 02 Oct 2017 20:30:46 GMT
Content-Length: 506
Content-Type: text/html; charset=utf-8
Cache-Control: no-cache, no-store

$ curl https://githublinker.herokuapp.com/q/npm/browserify
<!DOCTYPE html>
	<html>
	  <head>
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta charset="utf-8">
		<title>Application Error</title>
		<style media="screen">
		  html,body,iframe {
			margin: 0;
			padding: 0;
		  }
		  html,body {
			height: 100%;
			overflow: hidden;
		  }
		  iframe {
			width: 100%;
			height: 100%;
			border: 0;
		  }
		</style>
	  </head>
	  <body>
		<iframe src="//www.herokucdn.com/error-pages/application-error.html"></iframe>
	  </body>
	</html>%             
```

Perhaps some configuration has gone stale? At any rate, thanks so much for providing this service/extension in the first place. Having it break makes me realize how much I ❤️ it.

**Comment by stefanbuck** [comment]
Thanks for reporting this issue. According to the logs something was wrong with newrelic. I disabled newrelic and it seems to be working for now. I will have a closer look tomorrow.

**Comment by rreusser** [comment]
Working fine once more. Thanks so much for the prompt response!
